# Generated by Django 3.2.5 on 2021-07-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='private',
            field=models.BooleanField(default=True, verbose_name='Privado'),
        ),
    ]
