# Generated by Django 3.2.5 on 2021-07-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='private',
        ),
    ]
